blank_issues_enabled: false
contact_links:
  - name: Off-topic
    url: https://github.com/MajkiIT/polish-ads-filter/discussions/new
    about: Å»yczenia, powitania i inne sprawy niezwiÄ…zane z listami filtrÃ³w, czyli plotkujemy o wszystkim i o niczym ğŸ™‚
